version: '3'
services:
  # svelte-app:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
    # restart: always
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "4173:4173"
  #     - "5173:5173"


  backend:
    build: ./backend
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    volumes:
      - ./backend:/app
    restart: always
    environment:
      - MODULE_NAME=main
      - VARIABLE_NAME=app
    env_file:
      - ".env"
    ports:
      - "4000:4000"
    networks:
      app_net:
    depends_on:
      - postgresdb


  postgresdb:
    container_name: postgresdb
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "postgresdata:/var/lib/postgresql/data"
    restart: always
    networks:
      app_net:
    env_file:
      - ".env"


volumes:
  postgresdata:


networks:
  app_net:
