version: '3'
services:
  svelte-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - "4173:4173"
      - "5173:5173"


  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    restart: always
    env_file:
      - ".env"
    networks:
      app_net:
    depends_on:
      - postgresdb


  postgresdb:
    container_name: postgresdb
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "postgresdata:/var/lib/postgresql/data"
    restart: always
    networks:
      app_net:
    env_file:
      - ".env"


volumes:
  postgresdata:


networks:
  app_net:
